name: SPaySdk

options:
  deploymentTarget: 13.0
  groupSortPosition: top
  generateEmptyDirectories: false
  findCarthageFrameworks: false
  minimumXcodeGenVersion: '2.18.0'
  developmentLanguage: ru

settings:
  base:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES

packages:
  IQKeyboardManagerSwift:
    url: https://github.com/hackiftekhar/IQKeyboardManager.git
    from: 6.0.0
  Dynatrace-Static:
   url: https://github.com/Dynatrace/swift-mobile-sdk.git
   from: 8.0.0
  FingerprintPackage:
    path: ./FingerprintPack
  YandexMobileMetrica:
   url: https://github.com/yandexmobile/metrica-sdk-ios
   from: 4.5.2

targetTemplates:
  Framework:
    type: framework
    platform: iOS
    deploymentTarget: 13.0
    settings:
      base:
        MARKETING_VERSION: 1.2
  SPaySdk: 
    type: framework
    platform: iOS
    deploymentTarget: 13.0
    scheme: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.s.pay.SPaySdk
        BUILD_LIBRARY_FOR_DISTRIBUTION: true
        ONLY_ACTIVE_ARCH: false
        MARKETING_VERSION: 2.1.1
        OTHER_LDFLAGS:
          - $(inherited)
          - $(OTHER_LDFLAGS)
          - -ObjC
    sources:
      - path: ./SPaySdk
      - path: ./Generated
    dependencies:
      - package: Dynatrace-Static
      - package: FingerprintPackage
      - sdk: libresolv.9.tbd
      - framework: ./Lottie.xcframework
    info:
      path: ./SPaySdk/SupportingFiles/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: 6.0
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: FMWK
        CFBundleShortVersionString: 2.1.1
        CFBundleVersion: 2.1.1
        SDKVersion: "2.1.1"
  
targets:
  SPaySdkExample:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    scheme: {}
    sources:
       - path: ./SberPayExample
    settings:
      TARGETED_DEVICE_FAMILY: 1
      MARKETING_VERSION: 2.1
      CURRENT_PROJECT_VERSION: 39
      PRODUCT_BUNDLE_IDENTIFIER: com.team11.spay.sdk
      DEVELOPMENT_TEAM: 9CYS9A2HF7
      INFOPLIST_KEY_CFBundleDisplayName: SPayTest
      SWIFT_OBJC_BRIDGING_HEADER: SberPayExample/Presentation/ObjcCartVC/SberPayExample-Bridging-Header.h
    dependencies:
      - package: IQKeyboardManagerSwift
      - package: YandexMobileMetrica
      - target: SPaySdkDEBUG
        link: true
      - framework: ./SberIdSDK.xcframework
    preBuildScripts:
      - name: Swiftlint
        script: |
                export PATH="$PATH:/opt/homebrew/bin"

                if which swiftlint > /dev/null; then
                  swiftlint
                 else
                  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
        basedOnDependencyAnalysis: false
      - name: Swiftgen
        script: |
                swiftgen
        basedOnDependencyAnalysis: false
    info:
      path: ./SberPayExample/SupportingFiles/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen.storyboard
        CFBundleDisplayName: $(BUNDLE_DISPLAY_NAME)
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        NSLocationWhenInUseUsageDescription: Данные о местонахождении собираются и отправляются на сервер для безопасного проведения оплаты
        NSFaceIDUsageDescription: "Так вы подтвердите, что именно вы выполняете вход"
        LSSupportsOpeningDocumentsInPlace: true
        DTXAutoStart: false
        ITSAppUsesNonExemptEncryption: false
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLName: testapp
            CFBundleURLSchemes:
              - testapp
        NSAppTransportSecurity: 
          NSExceptionDomains:
            psi.gate1.spaymentsplus.ru:
              NSExceptionAllowsInsecureHTTPLoads: true
            ift.gate1.spaymentsplus.ru:
              NSExceptionAllowsInsecureHTTPLoads: true
            gate1.spaymentsplus.ru:
              NSExceptionAllowsInsecureHTTPLoads: true
            ift.gate2.spaymentsplus.ru:
              NSExceptionAllowsInsecureHTTPLoads: true
            cms-res.online.sberbank.ru:
              NSExceptionAllowsInsecureHTTPLoads: true
        UIFileSharingEnabled: true
        LSApplicationQueriesSchemes:
            - sberbankidexternallogin
            - sbolidexternallogin
        
  SPaySdk:
    templates:
      - SPaySdk
    sources:
      - path: ./PROD-SPay
    settings:
      base:
        OTHER_SWIFT_FLAGS: "-DSDKPROD"
  SPaySdkDEBUG:
    templates:
      - SPaySdk
    sources:
      - path: ./DEBUG-SPay
    settings:
      base:
        OTHER_SWIFT_FLAGS: "-DSDKDEBUG"
aggregateTargets:
  SPayFramework:
    buildScripts:
      - path: ./build.sh

